# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58ca594be4a72a4bd9d7da9a448acb7e55e2f053c61951b2c18527d9fab6d2a7c78fdc367f70ca6566f3b9f8aaf884930bbeefedd9f6fe77718d95446c64dd85

test:
  secret_key_base: 56a055e0986830dad5ce669e8cadfb79eaead0cb1c86125f9d7e20c1e344fdd760a28674eb903d877680a105a13ab1623756beecf8f77debb430f32b6d663139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
